name: Publish Action

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  
    steps:
      - uses: actions/checkout@v1

      - name: Run Install
        run: yarn install

      - name: Run Building
        if: success()
        run: yarn build

      - name: Publish extension
        if: success()
        run: yarn run publish
