name: Publish Action

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  
    steps:
      - uses: actions/checkout@v1
      - name: Start building
        run: echo The ${{ github.event_name }} event triggered this step.

      - name: Run Install
        run: yarn install

      - name: Run Building
        if: success()
        run: yarn build

      - name: Publish extension
        if: success()
        run: |
          yarn run webstore upload --source ./build --extension-id $EXTENSION_ID --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token $REFRESH_TOKEN
