name: Realese Action

on:
  push:
    branches:
    - master
    - refs/tags/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Install
        run: |
          echo "Realese Action"
