name: Realese Action

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Start building
        run: echo The ${{ github.event_name }} event triggered this step.
        
      - name: Run Install
        run: yarn install
        
      - name: Run Building
        run: yarn build
        
      - name: Run pack
        run: |
          tag_version=  $(git describe --tags `git rev-list --tags --max-count=1`) || echo "Cann't get a tag. Exit" && exit;
          echo $tag_version
