name: Release Action

on:
  push:
    branches: 
      - master
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}

    steps:
      - uses: actions/checkout@v1
      - name: Start building
        run: echo The ${{ github.event_name }} event triggered this step.

      - name: Run Install
        run: yarn install

      - name: Run Building
        if: success()
        run: yarn build

      - name: Run Pack
        if: success()
        run: |
          TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`) || { echo "\⛔️ Unable to get a tag.\n"; exit 1;  };
          echo ::set-env name=TAG_VERSION::${TAG_VERSION}
          zip -r twitter_counter.$TAG_VERSION.zip build/

      - name: Create Release
        if: success()
        run: ./.github/scripts/release_creator.sh

      - name: Upload release file
        if: success()
        run: ./.github/scripts/release_uploader.sh
