name: Release Action

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Start building
        run: echo The ${{ github.event_name }} event triggered this step.

      - name: Run Install
        run: yarn install

      - name: Run Building
        run: yarn build

      - name: Run pack
        run: |
          # TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`) || { echo "\⛔️ Unable to get a tag.\n"; exit 1;  };
          TAG_VERSION=2.0.0
          echo ::set-env name=TAG_VERSION::${TAG_VERSION}
          zip -r twitter_counter.$TAG_VERSION.zip build/

      - name: Upload realese
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        run: ./.github/scripts/release_uploader.sh
